//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetEaseController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class CommandSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommandSetting defaultInstance = ((CommandSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommandSetting())));
        
        public static CommandSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F1")]
        public string PlayPause {
            get {
                return ((string)(this["PlayPause"]));
            }
            set {
                this["PlayPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F2")]
        public string PrevSong {
            get {
                return ((string)(this["PrevSong"]));
            }
            set {
                this["PrevSong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F3")]
        public string NextSong {
            get {
                return ((string)(this["NextSong"]));
            }
            set {
                this["NextSong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F4")]
        public string VolUp {
            get {
                return ((string)(this["VolUp"]));
            }
            set {
                this["VolUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F5")]
        public string VolDown {
            get {
                return ((string)(this["VolDown"]));
            }
            set {
                this["VolDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+F8")]
        public string LikeMusic {
            get {
                return ((string)(this["LikeMusic"]));
            }
            set {
                this["LikeMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WIN")]
        public string Win {
            get {
                return ((string)(this["Win"]));
            }
            set {
                this["Win"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VOLUME_MUTE")]
        public string VB_Mute {
            get {
                return ((string)(this["VB_Mute"]));
            }
            set {
                this["VB_Mute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+MEDIA_STOP")]
        public string VB_OutToggle {
            get {
                return ((string)(this["VB_OutToggle"]));
            }
            set {
                this["VB_OutToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VOLUME_UP")]
        public string VB_VolUp {
            get {
                return ((string)(this["VB_VolUp"]));
            }
            set {
                this["VB_VolUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VOLUME_DOWN")]
        public string VB_VolDown {
            get {
                return ((string)(this["VB_VolDown"]));
            }
            set {
                this["VB_VolDown"] = value;
            }
        }
    }
}
